### ISSUE TITLE
searx.me doesn't display Google results

### ISSUE THREAD

**Issue by ghost** [searx/searx#1089]
I don't know if this is the appropriate place to ask since this is an issue specific to a single instance of searx, but since yesterday I can't seem to obtain results from Google using searx.me .
If I disable all engines but Google I get no results at all. I tried other public instances, including search.homecomputing.fr and searx.info and they don't seem to have this problem.
Does anyone else have similar issues?

**Comment by dalf** [comment]
I confirm. May be related to 9ab8536479f30960e79ed1 ?

**Comment by asciimoo** [comment]
Sorry, I misconfigured something after the upgrade to 0.13.0. It should work now.

Btw, I don't recommend to use searx.me, it is still very crowded and has errors because of the massive amount of requests. Check out other public instances: https://github.com/asciimoo/searx/wiki/Searx-instances or host your own =)

**Comment by ghost** [comment]
Nope, it still doesn't seem to work. Tried on Firefox 57.0 and Chromium 62.0.3202.94 with a clean history and cache, and with no extensions.
Can others confirm?

EDIT: same problem with searx.info. This isn't an issue specific to searx.me anymore.

**Comment by asciimoo** [comment]
This is strange.. It doesn't throw any error and it works on my local instance...

**Comment by asciimoo** [comment]
Seems like google is throwing CAPTCHAs. I still don't know why and how to solve it. Any ideas?

Perhaps it is related to 9ab8536 as @dalf mentioned.

**Comment by asciimoo** [comment]
I reverted 9ab8536 on searx.me and google engine works again. So it's probably related to 9ab8536.

Any ideas how to fix the language setting without getting CAPTCHAs?

**Comment by asciimoo** [comment]
Hopefully 6fdb6640 and 6eb95038 will solve both problems. I've deployed it to searx.me.

**Comment by muppeth** [comment]
Is there a way to solve the captcha issue once it occurs?
I updated to latest searx (git pull of master) but google still timesout with 503 error. Checking google search with links from the searx host brings me to the warning page with captcha.

**Comment by asciimoo** [comment]
@muppeth upgrade to the latest master and wait few minutes/hours before restarting searx. The captcha page says  that "[...] The block will expire shortly after those requests stop.".

**Comment by muppeth** [comment]
@asciimoo thanks. I've disabled google search engine until cooldown.

**Comment by dalf** [comment]
Technical note on search.py : We could imagine that an engine can throw a SearxThrottleException which gives how many minutes / hours to wait before to use this engine again. Then search.py can makes this request effective. It would avoid endless captcha (even if search.py already do that but I guess it doesn't wait enough because this is not the same use case)

**Comment by asciimoo** [comment]
Seems, the problem is solved. Feel free to reopen if you notice the opposite.

**Comment by muppeth** [comment]
Hmmm... Got Captcha'ed last evening already but I decided to update to 13.1 and swich off google search for few hours. Once enabled again it worked fine. This mornining noticed we are blocked again :(

**Comment by asciimoo** [comment]
@muppeth interesting.. It works fine on searx.me since 0.13.1. Is your instance public?

**Comment by muppeth** [comment]
@asciimoo yes it is.

**Comment by asciimoo** [comment]
@muppeth perhaps some scripts abuse it and the blocking is valid. Do you use firewall or any other defense mechanism to protect your instance? I'm using [filtron](https://github.com/asciimoo/filtron) on searx.me.

**Comment by Pofilo** [comment]
I have the same issue on my own instance since yesterday (13.1 installed).
It used to work fine before and I don't have anything in the logs.
Is there a version before 0.13 where it used to work ?

**Comment by Pofilo** [comment]
It is due to the CAPTCHAs, was it supposed to be solved ?

**Comment by asciimoo** [comment]
@Pofilo it is solved in v0.13.1. It works well on searx.me. Have you tried to suspend google engine for 1-2 hours?

**Comment by Pofilo** [comment]
@asciimoo I move to v.0.13.1 the hour it was out !
In 21 hours without using Google, I still have the issue. 
I was also using autocomplete with Google (not since Yesterday tho).
Other thing, my researches are in french (fr-FR so google.fr), maybe it can be related.

**Comment by asciimoo** [comment]
This is strange.. Are you sure that nobody abuses your instance?

**Comment by muppeth** [comment]
@Pofilo You should definately enable access logs and try to follow for a while whats going on. In my case it was a bot sending enormous amount of same type queries for a day or two (<Artists> Download mp3 or <Some movie> Download etc). Then at some point it just stopped (I guess its the same bot jumping form one searx instance to another).

Setting up filtron (something I havent done yet) will probably save you from this happening in the future.

**Comment by Pofilo** [comment]
I'm the only one using my instance (logs are confirming that).
I will check more precisely if something on my server is talking to google (or if something talks to google through my server).

**Comment by dalf** [comment]
The old commit 52e615de is nearly the same, but if you have time, you can give a try :
https://raw.githubusercontent.com/asciimoo/searx/52e615dede8538c36f569d2cf07835427a9a0db6/searx/engines/google.py

**Comment by asciimoo** [comment]
@dalf If @Pofilo is using fr-FR, the code is identical on that call path I think, that's why I don't understand the bug.

**Comment by Pofilo** [comment]
Even in all languages I have the problem.
This is what I get from the logs:

`DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET /search?q=test&start=0&gws_rd=cr&gbv=1&lr=lang_en&ei=x HTTP/1.1" 302 405
DEBUG:urllib3.connectionpool:https://ipv4.google.com:443 "GET /sorry/index?continue=https://www.google.com/search%3Fq%3Dtest%26start%3D0%26gws_rd%3Dcr%26gbv%3D1%26lr%3Dlang_en%26ei%3Dx&q=EgSVyjQ0GJmpmdEFIhkA8aeDS3PI0bodzHZIBxboq0U--AsOajJWMgFy HTTP/1.1" 503 2702`

We can see the request is correct according to https://github.com/asciimoo/searx/commit/6fdb6640d9e644860f60bf9cd59847c2d359fc8a.

My instance was shut down all the week-end + monday and nothing went to google from the IP of my server, I don't really understand what's happening ..

_EDIT: should I open a new ticket about that ?_

**Comment by ghost** [comment]
Got the same problem after upgrading to 13.1. As soon as i switch back to my 12.0 backup everything works flawlessly.

**Comment by Pofilo** [comment]
@himbeere @asciimoo okay, thanks for the information.
I'll switch back to 12.0 and give you a feedback too.

**Comment by Pofilo** [comment]
Okay, after the switch back, it was not working either (I mean google results).
After 1 day off (instance of searx down), I still have the problem too (in 12.0).

However in 13.1, I don't understand why https://github.com/asciimoo/searx/commit/6fdb6640d9e644860f60bf9cd59847c2d359fc8a is not working for me.

**Comment by Pofilo** [comment]
Okay, I also have (only used by myself with no request on google) an instance of openvpn on my server and somehow, [google is able to detect it and block it](https://support.google.com/websearch/answer/86640?hl=en).

I'll try to make some researches about that to solve this problem.

**Comment by ghost** [comment]
I just tried again. Now i have results from google with version 13.1. Strange. But good enough for me. 

cheers
t.

**Comment by ghost** [comment]
And problem occurs again.  searx - 0.13.1 -> google (unexpected crash: CAPTCHA required)

**Comment by Pofilo** [comment]
Me too, the problem seems not to be related to searx directly.
When searx is down for a week, I still have the issue (openvpn and unbound down).

I don't know if my server has a service sending requests to google (I really don't think so) or if my IP has somehow been blacklisted at a moment or maybe [this reason](https://www.reddit.com/r/VPN/comments/674rq8/selfhosted_vpn_on_digitalocean_and_google_captchas/dgo9moz/).

**Comment by ghost** [comment]
OK, i see. I thought 12.0 worked without problems. I have to re-check. Maybe 12.0 just misses the error message?

**Comment by ghost** [comment]
Hm. Switched back to 12.0. There is no error message regarding google. But the results contain no results from google.

**Comment by Pofilo** [comment]
The result of a request asking for a captcha looks like that:

`
https://ipv4.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dtest...
`

So as we have a response, I guess this is why there is no logs about that.
