### ISSUE TITLE
After latest update error 502 bad gateway

### ISSUE THREAD

**Issue by joshu9h** [searx/searx#1110]
Press store button in preference gives error 502 bad gateway
nginx error log
2017/12/06 18:43:04 [error] 1475#1475: *678 upstream sent too big header while reading response header from upstream, client: , server: , request: "POST /preferences HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/searx/socket:", host: ""

**Comment by xinomilo** [comment]
using nginx and the latest update, no such error here. try restarting uwsgi and maybe check for stuck processes. uwsgi log might also have more info.

**Comment by joshu9h** [comment]
Uwsgi log gives a HTTP/1.1 302
uwsgi log
https://pastebin.com/0AF5xGCK

**Comment by joshu9h** [comment]
If i only do a git pull it's working
when i do after  a git stash apply i get the error 502 bad gateway
how does this work (dig)
git status showed me my problem
i

**Comment by HuKaers** [comment]
Since 6dec i do have the same problem here (uwsgi+nginx). Fresh install doesnt help.
How did you resolve this?

**Comment by asciimoo** [comment]
Seems like the problem is in nginx and in filtron also.
You have to increase the proxy header buffer size in nginx:
```
http {
  proxy_buffer_size   128k;
  proxy_buffers   4 256k;
  proxy_busy_buffers_size   256k;
}
```
filtron patch is in progress.

**Comment by asciimoo** [comment]
filtron fixed in https://github.com/asciimoo/filtron/commit/d200b21c4284f21d2cea42f8d6d13b1fa9d8601c

**Comment by joshu9h** [comment]
I thought i found it but still the same problem bad gateway 502
asciimoo where do i put
http {
  proxy_buffer_size   128k;
  proxy_buffers   4 256k;
  proxy_busy_buffers_size   256k;
}
I tried nginx.conf no result
 upstream sent too big header while reading response header from upstream,

**Comment by knyfe** [comment]
Same problem here. Fresh install of Ubuntu 16.04, nginx, uwsgi and searx. nginx/error.log shows "upstream sent too big header while reading response header from upstream" even with proxy buffer settings in nginx.conf and a system restart.

**Comment by asciimoo** [comment]
I've added it to `/etc/nginx/nginx.conf`'s `http` section and it solved the problem for me.

**Comment by knyfe** [comment]
Yep, that is where I put it. Still no luck. Same "too big header" error in log, 502 Bad Gateway on the site, and no cookies. Perhaps I am missing other needed nginx.conf settings or require different proxy buffer settings than yours? At this point I just have the default nginx.conf file with the added proxy buffer settings. My previous setup was working beautifully prior to my attempt to update yesterday. I've since installed on a completely new server and getting the same errors.

**Comment by joshu9h** [comment]
Same here no luck also updated nginx from1.10 to 1.12
the extra nginx error debug 
gives
2017/12/09 23:03:38 [debug] 1078#1078: *1 SSL_read: -1
2017/12/09 23:03:38 [debug] 1078#1078: *1 SSL_get_error: 2
si i update to version 1.12 but the same

**Comment by joshu9h** [comment]
[enh] add dark version of oscar/logicodev 
git checkout 46fb0d860e35a45658969c4e2ac306a1072bc331
Works fine and
[enh] make custom oscar option configurable from url 
git checkout e060aedc16bb2b9e5c1ee3fc69a0e07a3576a80c
gives bad gateway 502

**Comment by joshu9h** [comment]
Did some testing updated to the latest master 
if i hash the following in preferences.py
line 308 #else:
line 309 #self.unknown_params[user_setting_name] = user_setting
It works no errors 
The only thing the oscar Logicodev dark doesn't work 
Hope this will make some understanding about the 502 bad gateway problem

**Comment by kvch** [comment]
@knyfe I put those two options under `server` without `http` in nginx and that solved the issue. Also, updated my filtron to handle bigger headers.

```conf
server {
    ssl on;

    /* my config */

    location / {
            proxy_set_header        Host    $http_host;
            /* more config */
    }
    proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size   256k;
}

```
