### ISSUE TITLE
Searx image-searches disrupted by Google, Bing, 500px etc

### ISSUE THREAD

**Issue by PFCS1976** [searx/searx#1338]
Failed searches and messages such as this - "google images (unexpected crash: No JSON object could be decoded), 500px (unexpected crash: 'photos')" - are happening to me constantly on every searx instance I visit (this has been going on for days)

**Comment by ghost** [comment]
Same here. I find it quite annoying :/

**Comment by dagaz** [comment]
Also same here.
(Searx running as a docker container build directly from sources.)

**Comment by sven222** [comment]
Same here, running on Debian 9 with nginx, latest master branch

**Comment by bourrel** [comment]
Unfortunately [500px shut down its API](https://support.500px.com/hc/en-us/articles/360002435653-API-). IMO the best solution for the moment is to deactivate 500px (maybe set it deactivated by default ?) from the engines and wait till a solution is found.

I can't reproduce the google images crash neither on searx.me nor in my personnal instance. Are you sure the instances you use are up-to-date ?

**Comment by Failure404** [comment]
Same here:
google images (unexpected crash: No JSON object could be decoded)

**Comment by asciimoo** [comment]
Update to the latest master, google images is fixed on the master branch. Also, I'll release a new version (0.15.0) soon.

**Comment by asciimoo** [comment]
I've removed 500px, google/bing works fine on the latest master for me.

**Comment by Ryonez** [comment]
This is defiantly still an issue:

![image](https://user-images.githubusercontent.com/16157130/51702843-ba492c00-2079-11e9-8e87-3cd1b69dec96.png)

From the logs:

```
Traceback (most recent call last):
File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
search_results = search_one_request(engine, query, request_params)
File "/usr/local/searx/searx/search.py", line 87, in search_one_request
return engine.response(response)
File "/usr/local/searx/searx/engines/www500px.py", line 56, in response
for result in response_json['photos']:
KeyError: 'photos'
ERROR:searx.search:engine google images : exception : No JSON object could be decoded

Traceback (most recent call last):
File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
search_results = search_one_request(engine, query, request_params)
File "/usr/local/searx/searx/search.py", line 87, in search_one_request
return engine.response(response)
File "/usr/local/searx/searx/engines/google_images.py", line 69, in response
g_result = loads(resp.text)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR:searx.search:engine 500px : exception : 'photos'

Traceback (most recent call last):
File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
search_results = search_one_request(engine, query, request_params)
File "/usr/local/searx/searx/search.py", line 87, in search_one_request
return engine.response(response)
File "/usr/local/searx/searx/engines/www500px.py", line 56, in response
for result in response_json['photos']:
KeyError: 'photos'
ERROR:searx.search:engine bing images : exception : expected string or buffer

Traceback (most recent call last):
File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
search_results = search_one_request(engine, query, request_params)
File "/usr/local/searx/searx/search.py", line 87, in search_one_request
return engine.response(response)
File "/usr/local/searx/searx/engines/bing_images.py", line 111, in response
thumb_json_data = loads(_quote_keys_regex.sub(r'\1"\2": \3', link.attrib.get('mad')))
TypeError: expected string or buffer
WARNING:searx.search:engine timeout: flickr

ERROR:searx.search:engine flickr : HTTP requests timeout(search duration : 3.29820203781 s, timeout: 3.0 s) : Timeout
```

Running the latest docker image from `wonderfall/searx`. It does appear the image is out of date by 6 months.
